export const CONSTANTS = {
    formPrice: 110,
    formIdNumber: 99991,
    dobProofSelection : [
        "Please Select",
        "Birth Certificate issued by the Municipal Authority or any office authorized to issue Birth and Death certificate by the registrar of Birth and Death of the Indian Consulate",
        "Pension payment order",
        "Marriage Certificate issued by Registrar of Marriages",
        "Marticulation Certificate",
        "Passport",
        "Driving Licence",
        "Domicile certificate issued by the Government",
        "Affidavit sworn before a magistrate, stating the date of birth",
        "Marticulation Marksheet of recognised board",
        "AADHAAR Card issued by the Unique Identification Authority of India",
        "Elector's photo identity card",
        "Photo identity card issued by Central Government or State Government Public Sector Undertaking",
        "Central Government Health Scheme Card",
        "Ex-Servicemen Contributory Health Scheme photo card"
    ],
    addressProofSelection : [
        "Please Select",
        "Latest property tax assesment order",
        "Depository account statement (Not more than 3 month old from date of application)",
        "Credit card statement (Not more than 3 month old from date of application)",
        "Bank Account statement/Passbook (Not more than 3 month old from date of application)",
        "Landline Telephone Bill (Not more than 3 month old from date of application)",
        "Certificate of Address signed by Municipal Councilor",
        "Driving Licence",
        "Passport",
        "Property Registration Document",
        "Electricity Bill (Not more than 3 month old from date of application)",
        "Bank Account Statement in the country of residence (Not more than 3 month old from date of application)",
        "Employer certificate in original",
        "Elector's photo identity card",
        "Certificate of Address Signed by a Gazetted Officer",
        "Passport of the spouse",
        "Post office passbook having address of the applicant",
        "Domicile certificate issued by the Government",
        "Allotment letter of accomodation issued by Central or State Government of not more than three year old",
        "Certificate of Address signed by a Member of Legislative Assembly",
        "Certificate of Address signed by a Member of Parliament",
        "AADHAAR Card issued by the Unique Identification Authority of India",
        "Consumer Gas connection card or book or piped gas bill (Not more than 3 month old from date of application)",
        "Water Bill (Not more than 3 month old from date of application)",
        "Broadband Connection bill (Not more than 3 month old from date of application)"
    ],
    identityProofSelection : [
        "Please Select",
        "Certificate of Address Signed by a Gazetted Officer",
        "Certificate of Address signed by a Member of Legislative Assembly",
        "Certificate of Address signed by a Member of Parliament",
        "Certificate of Address signed by Municipal Councilor",
        "Driving Licence",
        "Passport",
        "Arm's Licence",
        "Central Government Health Scheme Card",
        "Ex-Servicemen Contributory Health Scheme photo card",
        "Bank Certificate in original on letter head from the branch (along with name and stamp of the issuing officer) containing duly attested photograph and bank account number of the applicant",
        "Photo identity card issued by Central Government or State Government Public Sector Undertaking",
        "Pensioner Card having photograph of the applicant",
        "Elector's photo identity card",
        "Ration Card having photograph of the applicant",
        "AADHAAR Card issued by the Unique Identification Authority of India"
    ],
    states : [
        "Please Select",
        "ANDAMAN AND NICOBAR ISLANDS",
        "ANDHRA PRADESH",
        "ARUNACHAL PRADESH",
        "ASSAM",
        "BIHAR",
        "CHANDIGARH",
        "CHHATISGARH",
        "DADRA & NAGAR HAVELI",
        "DAMAN & DIU",
        "DELHI",
        "GOA",
        "GUJARAT",
        "HARAYANA",
        "HIMACHAL PRADESH",
        "JAMMU & KASHMIR",
        "JHARKHAND",
        "KARNATAKA",
        "KERALA",
        "LAKHWADEEP",
        "MADHYA PRADESH",
        "MAHARASHTRA",
        "MANIPUR",
        "MEGHALAYA",
        "MIZORAM",
        "NAGALAND",
        "OSHIDA",
        "OUTSIDE INDIA",
        "PONDICHERRY",
        "PUNJAB",
        "RAJASTHAN",
        "SIKKIM",
        "TAMIL NADU",
        "TELENGANA",
        "TRIPURA",
        "UTTAR PRADESH",
        "UTTARAKHAND",
        "WEST BENGAL"
    ],
    coaSelection: [
        "Please Select",
        "Individual",
        "Firm",
        "Body of Individuals",
        "Hindu Undivided Family",
        "Association of Persons",
        "Local Authority",
        "Company",
        "Trust",
        "Artificial Juridical Person",
        "Government",
        "Limited Liability Partnership"
    ],
    addressProofSelectionForAJP: [
        "Please Select",
        "Agreement",
        "Certificate of registration issued by any other competent authority.",
        "Certificate of registration issued by charity commissioner.",
        "Certificate of registration issued by registrar of co-op Society",
        "Any Document originating from any central or state Govt. Department establishing identity of such person."
    ],
    addressProofSelectionForGovt: [
        "Please Select",
        "Any document originating from any central or state Govt. Department establishing address of such person"
    ],
    identityProofSelectionForGovt: [
        "Please Select",
        "Any document originating from any central or state Govt. Department establishing address of such person"
    ],
    addressProofSelectionForLLP: [
        "Please Select",
        "Copy of certificate of Registration issued by the Registrar of Firms/Limited liability partnerships"
    ],
    identityProofSelectionForLLP: [
        "Please Select",
        "Copy of certificate of Registration issued by the Registrar of Firms/Limited liability partnerships"
    ]
};